### ISSUE TITLE
Can't create webhook for specific event

### ISSUE THREAD

**Issue by snomos** [divvun/gut#170]
The following command:

```sh
gut hook create -m json -o giellalt -r 'lang-smj' -u 'https://giella.zulipchat.com/api/v1/external/github?api_key=SECRETKEY&stream=smj' -e "push"
```

returns the following error:

```
2021-01-15T11:01:15.364Z DEBUG gut::github::rest > POST: https://api.github.com/repos/giellalt/lang-smj/hooks
Failed because Unsuccessful request with status code: 422 Unprocessable Entity
```

Expected behavior:

The webhook is changed to fire on only the specified event, not everything as it is now.

@ZoeyR any idea what could be wrong?

**Comment by snomos** [comment]
Zulip (the recipient of the events) reacted with the following:

```quote
Notification Bot 13:05

Hi there! It looks like you tried to set up the Zulip GitHub integration,
but didn't correctly configure the webhook to send data in the JSON format
that this integration expects!
```

That seems strange, because I have done this before - but earlier I have always used the `-s` parameter, not `-u`.

**Comment by ZoeyR** [comment]
@snomos The create command _might_ not work if the webhook already exists, which it sounds like it does. Can you try deleting the webhook first and then recreating it?

**Comment by snomos** [comment]
Yup, that was it. Thanks a lot!

**Comment by snomos** [comment]
Reopened because I still can't create a webhook for a long list of (but not all) events. I am able to create for two, probably more, but the error message when you submit a long list of events for which the webhook should fire is not very helpful.

This is the command I send:

```sh
gut hook create -m json -o giellalt -r 'lang-smj' \
  -u 'https://giella.zulipchat.com/api/v1/external/github?api_key=SECRETKEY&stream=smj' \
  -e check_run code_scanning_alert commit_comment create delete deploy_key \
   deployment deployment_status fork github_app_authorization gollum installation \
   installation_repositories issue_comment issues label marketplace_purchase member \
   membership milestone organization org_block package ping project_card project_column \
   project public pull_request pull_request_review pull_request_review_comment push \
   release repository_dispatch repository repository_import repository_vulnerability_alert \
   secret_scanning_alert security_advisory sponsorship star status team team_add watch \
   workflow_dispatch workflow_run
```

And this is the error message I get in return:

```
Failed because Unsuccessful request with status code: 422 Unprocessable Entity
```

Presumably one of the event names is wrong or invalid, but I have no idea which one. If the error message would contain more information about what is broken, that would be helpful.

**Comment by snomos** [comment]
I worked it out - had to remove all events that are not available for repositories.
