### ISSUE TITLE
make `main` the new default branch

### ISSUE THREAD

**Issue by snomos** [divvun/gut#172]
When asking `gut` to create a new repo (with data from a template) it will do so in a branch named `master`. As long as one is working only locally, it is easy to change, but it would be very nice to have `gut` follow the new naming standard of having `main` as the default branch name.

**Comment by bbqsrc** [comment]
Fixed in https://github.com/divvun/gut/commit/ea26bdb0c6fb6227668c15a65746a2d90f5806f1
