### ISSUE TITLE
`gut apply template` hangs on `lang-smn`

### ISSUE THREAD

**Issue by snomos** [divvun/gut#181]
All other languages are fine. To repeat:

- `cd giellalt`
- `gut clone -o giellalt -r lang-smn`
- `gut clone -o giellalt -r template-lang-und`
- `gut template apply -o giellalt -r '^lang-smn' -t template-lang-und`

Notice that:
- it finds the correct hashes of both prev and current rev of `template-lang-und`
- nothing further happens - it just hangs
- no other languages are affected, all the rest merge just fine
- after aborting, `gut` "knows" a template merge is underway, although nothing has happened to the template. To get back to a clean state, one has to run `gut template apply --abort -o giellalt -r '^lang-smn' -t template-lang-und` (cf the added `--abort` option), but other than aborting the template merge, nothing changes - it is just as impossible to merge anew afterwords.

No debug info or other info is given as to why. I have no idea how to debug this error. I even tried to clone the `lang-smn` repo anew, it didn't help.

**Comment by snomos** [comment]
@zoomix @ZoeyR I guess we need help from TheTC on this one. It is very annoying, nice if you could have a look soon. Or if @ZoeyR is not the correct one, please ping another person 🙂 .

**Comment by snomos** [comment]
@flammie I saw that you did a template merge including `lang-smn`. Did you have any issues?

**Comment by flammie** [comment]
I think it went fine, though since I used `lang-smn` when making the new feature so I accidentally got `.rej` and `.orig` files in.

**Comment by snomos** [comment]
After @flammie 's round of template updates, the bug is gone, everything is working normally again. I have no idea what happened, but there is no point in hunting a ghost, so I'll just close.
