### ISSUE TITLE
Failed to authenticate SSH session

### ISSUE THREAD

**Issue by Phaqui** [divvun/gut#184]
Cannot pull a repository that is already cloned, getting an SSH failure. The repository was cloned with
`git clone git@github.com:giellalt/dict-sme-nob`, and my ssh key is password protected.

```
anders@debian:~/gut$ gut pull -o giellalt -r dict-sme-nob
 2023-09-27T07:18:40.084Z DEBUG gut > Arguments: Args { command: Pull(PullArgs { organisation: Some("giellalt"), regex: Some(Filter { regex: Regex("dict-sme-nob") }), stash: false, merge: false }) }
 2023-09-27T07:18:40.084Z INFO  gut::commands::pull > Processing repo dict-sme-nob
+------------------------------------------------------+
| Repo          Pull Status  Repo Status  Stash Status |
+======================================================+
| dict-sme-nob       Failed        Clean             - |
+------------------------------------------------------+
There 1 errors when process command:

+------------------------------------------------------------------------------------------------+
| Repo          Error                                                                            |
+================================================================================================+
| dict-sme-nob  Failed to authenticate SSH session: Unable to extract public key from private ke |
|               y file: Wrong passphrase or invalid/unrecognized private key file format; class= |
|               Ssh (23)                                                                         |
+------------------------------------------------------------------------------------------------+
```

**Comment by Phaqui** [comment]
One workaround is to add the key to ssh-agent, as described in

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

After doing this, the same command executes cleanly.

I suspect that it's difficult to handle having to get the key from the user interactively when doing batch operations (or even just programmatically at all) - due to the very fact that my understanding is that requiring user input of the passphrase when the key is being used, is the entire purpose of having keys be passphrase-protected in the first place.

Would a possible solution to this maybe just be to mark this as "wont-fix" (really: "cant-fix") - while documenting having to use the ssh agent when the key is passphrase protected (to let the key be used without having to type the passphrase on every use)?

**Comment by snomos** [comment]
> Would a possible solution to this maybe just be to mark this as "wont-fix" (really: "cant-fix") - while documenting having to use the ssh agent when the key is passphrase protected (to let the key be used without having to type the passphrase on every use)?

Yes, that seems reasonable. I will add this to the user documentation and to the README.

**Comment by snomos** [comment]
Documentation updated. Closing.
