### ISSUE TITLE
Decide Multirepo grouping config format

### ISSUE THREAD

**Issue by lenguyenthanh** [divvun/gut#37]
- Decide group data structure
- Where to store? Git notes or a git metadata repository?

Please more detail here: https://gist.github.com/snomos/58602cfaae4217f3736e872ccb47d77f#multirepo-grouping

**Comment by snomos** [comment]
See comment in issue #43 .

**Comment by ZoeyR** [comment]
I like the proposed idea of using github labels. That would also make it clear from the github UI what group a repo was in.

**Comment by bbqsrc** [comment]
We'll go with labels for now and change later if we need to; it's the path of least resistance.

**Comment by snomos** [comment]
No multirepo grouping, using labels instead. Closed.
