### ISSUE TITLE
Assign team X to group Y

### ISSUE THREAD

**Issue by lenguyenthanh** [divvun/gut#41]
Does this mean assign team X for all repositories on group Y?
What happen if we add/remove new repositories to group later?

**Comment by snomos** [comment]
> Does this mean assign team X for all repositories on group Y?

Yes.

> What happen if we add/remove new repositories to group later?

I think the idea was to use this as a shorthand for assigning a bunch of repos to a team. So if we instead to it like:

- add repos [matching regex|matching label/group] to team X

that would be all we need. Updates to the repos assigned to a team can then be handled manually later on, when need be.

**Comment by snomos** [comment]
No multirepo grouping, using labels instead. Closed.
