### ISSUE TITLE
Assign repo X to group Y

### ISSUE THREAD

**Issue by lenguyenthanh** [divvun/gut#42]
If a new group Y is a production group, repo X should automatically be added to CD for group Y

**Comment by snomos** [comment]
See notes in #43 .

**Comment by bbqsrc** [comment]
The CD aspect is out of scope for this issue and is managed by the CI services.

**Comment by lenguyenthanh** [comment]
We use topic to manage grouping so we can use `topic add` command to add a topic to a repository.
